### ISSUE TITLE
gold_add, bad request

### ISSUE THREAD

**Issue by apseyed** [peoplepattern/crowdflower#3]
I ran into that error for gold_add() getting:

Traceback (most recent call last):
  File "foo.py", line 185, in <module>
    methods[arg]()
  File "foo.py", line 143, in create
    job.gold_add('foo', 'foo_gold')
  File "/crowdflower/crowdflower/job.py",
line 241, in gold_add
    res = self._connection.request('/jobs/%s/gold' % self.id,
method='PUT', params=params)
  File /crowdflower/crowdflower/connection.py",
line 70, in request
    res = self.send_request(req)
  File "/crowdflower/crowdflower/connection.py",
line 61, in send_request
    raise CrowdFlowerError(req, res)
crowdflower.exception.CrowdFlowerError: CrowdFlowerError: 400 Bad
Request at https://api.crowdflower.com/v1/jobs/690982/gold

**Comment by apseyed** [comment]
from crowdflower support (please advise, also their solution doesn't scale very well):

"Our engineers spent a significant time looking into your request and determined that the best option is for you to use the API to upload units. Then go to the data page of the job, and click the 'Convert Uploaded To Test Questions' button. The gold units, when uploaded, need to have a column called '_golden'. Any row that has that column set to 'true' will be turned into gold when you hit the above mentioned button.

We don't have an API route to accomplish this, and the team was curious where you got the command that you are using, the '/job/job_id/golds/' route? It looks like we never supported that as an API command.

Thanks
M"
